INSERT INTO m_district (district_id, district_name, state_id) VALUES (603, 'NICOBARS', 35); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (632, 'NORTH AND MIDDLE ANDAMAN', 35); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (602, 'SOUTH ANDAMANS', 35); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (745, 'Alluri Sitharama Raju', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (744, 'Anakapalli', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (502, 'ANANTAPUR', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (753, 'Annamayya', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (750, 'Bapatla', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (503, 'CHITTOOR', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (505, 'EAST GODAVARI', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (748, 'Eluru', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (506, 'GUNTUR', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (746, 'Kakinada', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (747, 'Konaseema', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (510, 'KRISHNA', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (511, 'KURNOOL', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (755, 'Nandyal', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (749, 'NTR', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (751, 'Palnadu', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (743, 'Parvathipuram Manyam', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (517, 'PRAKASAM', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (515, 'SPSR NELLORE', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (519, 'SRIKAKULAM', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (754, 'Sri Sathya Sai', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (752, 'Tirupati', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (520, 'VISAKHAPATANAM', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (521, 'VIZIANAGARAM', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (523, 'WEST GODAVARI', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (504, 'Y.S.R.', 28); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (628, 'ANJAW', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (229, 'CHANGLANG', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (230, 'DIBANG VALLEY', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (231, 'EAST KAMENG', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (232, 'EAST SIANG', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (718, 'KAMLE', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (677, 'KRA DAADI', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (233, 'KURUNG KUMEY', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (724, 'LEPARADA', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (234, 'LOHIT', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (666, 'LONGDING', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (235, 'LOWER DIBANG VALLEY', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (719, 'LOWER SIANG', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (236, 'LOWER SUBANSIRI', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (678, 'NAMSAI', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (723, 'PAKKE KESSANG', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (237, 'PAPUM PARE', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (725, 'SHI YOMI', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (679, 'SIANG', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (238, 'TAWANG', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (239, 'TIRAP', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (240, 'UPPER SIANG', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (241, 'UPPER SUBANSIRI', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (242, 'WEST KAMENG', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (243, 'WEST SIANG', 12); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (739, 'BAJALI', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (616, 'BAKSA', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (280, 'BARPETA', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (705, 'Biswanath', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (281, 'BONGAIGAON', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (282, 'CACHAR', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (708, 'CHARAIDEO', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (612, 'CHIRANG', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (283, 'DARRANG', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (284, 'DHEMAJI', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (285, 'DHUBRI', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (286, 'DIBRUGARH', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (299, 'DIMA HASAO', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (287, 'GOALPARA', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (288, 'GOLAGHAT', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (289, 'HAILAKANDI', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (709, 'HOJAI', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (290, 'JORHAT', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (291, 'KAMRUP', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (618, 'KAMRUP METRO', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (292, 'KARBI ANGLONG', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (293, 'KARIMGANJ', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (294, 'KOKRAJHAR', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (295, 'LAKHIMPUR', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (706, 'MAJULI', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (296, 'MARIGAON', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (297, 'NAGAON', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (298, 'NALBARI', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (300, 'SIVASAGAR', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (301, 'SONITPUR', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (707, 'SOUTH SALMARA MANCACHAR', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (302, 'TINSUKIA', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (617, 'UDALGURI', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (710, 'WEST KARBI ANGLONG', 18); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (188, 'ARARIA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (611, 'ARWAL', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (189, 'AURANGABAD', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (190, 'BANKA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (191, 'BEGUSARAI', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (192, 'BHAGALPUR', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (193, 'BHOJPUR', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (194, 'BUXAR', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (195, 'DARBHANGA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (196, 'GAYA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (197, 'GOPALGANJ', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (198, 'JAMUI', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (199, 'JEHANABAD', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (200, 'KAIMUR (BHABUA)', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (201, 'KATIHAR', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (202, 'KHAGARIA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (203, 'KISHANGANJ', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (204, 'LAKHISARAI', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (205, 'MADHEPURA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (206, 'MADHUBANI', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (207, 'MUNGER', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (208, 'MUZAFFARPUR', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (209, 'NALANDA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (210, 'NAWADA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (211, 'PASHCHIM CHAMPARAN', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (212, 'PATNA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (213, 'PURBI CHAMPARAN', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (214, 'PURNIA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (215, 'ROHTAS', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (216, 'SAHARSA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (217, 'SAMASTIPUR', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (218, 'SARAN', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (219, 'SHEIKHPURA', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (220, 'SHEOHAR', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (221, 'SITAMARHI', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (222, 'SIWAN', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (223, 'SUPAUL', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (224, 'VAISHALI', 10); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (44, 'CHANDIGARH', 4); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (646, 'BALOD', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (644, 'BALODA BAZAR', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (649, 'BALRAMPUR', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (374, 'BASTAR', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (650, 'BEMETARA', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (636, 'BIJAPUR', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (375, 'BILASPUR', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (376, 'DANTEWADA', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (377, 'DHAMTARI', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (378, 'DURG', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (645, 'GARIYABAND', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (734, 'Gaurella Pendra Marwahi', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (379, 'JANJGIR-CHAMPA', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (380, 'JASHPUR', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (382, 'KABIRDHAM', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (381, 'KANKER', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (643, 'KONDAGAON', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (383, 'KORBA', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (384, 'KOREA', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (385, 'MAHASAMUND', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (647, 'MUNGELI', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (637, 'NARAYANPUR', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (386, 'RAIGARH', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (387, 'RAIPUR', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (388, 'RAJNANDGAON', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (642, 'SUKMA', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (648, 'SURAJPUR', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (389, 'SURGUJA', 22); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (77, 'CENTRAL', 7); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (78, 'EAST', 7); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (79, 'NEW DELHI', 7); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (80, 'NORTH', 7); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (81, 'NORTH EAST', 7); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (82, 'NORTH WEST', 7); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (671, 'SHAHDARA', 7); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (83, 'SOUTH', 7); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (670, 'South East', 7); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (84, 'SOUTH WEST', 7); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (85, 'WEST', 7); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (551, 'NORTH GOA', 30); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (552, 'SOUTH GOA', 30); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (438, 'AHMADABAD', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (439, 'AMRELI', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (440, 'ANAND', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (672, 'ARVALLI', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (441, 'BANAS KANTHA', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (442, 'BHARUCH', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (443, 'BHAVNAGAR', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (676, 'BOTAD', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (668, 'CHHOTAUDEPUR', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (444, 'DANG', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (674, 'DEVBHUMI DWARKA', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (445, 'DOHAD', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (446, 'GANDHINAGAR', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (675, 'GIR SOMNATH', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (447, 'JAMNAGAR', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (448, 'JUNAGADH', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (449, 'KACHCHH', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (450, 'KHEDA', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (451, 'MAHESANA', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (669, 'Mahisagar', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (673, 'MORBI', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (452, 'NARMADA', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (453, 'NAVSARI', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (454, 'PANCH MAHALS', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (455, 'PATAN', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (456, 'PORBANDAR', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (457, 'RAJKOT', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (458, 'SABAR KANTHA', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (459, 'SURAT', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (460, 'SURENDRANAGAR', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (641, 'TAPI', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (461, 'VADODARA', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (462, 'VALSAD', 24); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (58, 'AMBALA', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (59, 'BHIWANI', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (701, 'CHARKI DADRI', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (60, 'FARIDABAD', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (61, 'FATEHABAD', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (62, 'GURUGRAM', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (63, 'HISAR', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (64, 'JHAJJAR', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (65, 'JIND', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (66, 'KAITHAL', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (67, 'KARNAL', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (68, 'KURUKSHETRA', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (69, 'MAHENDRAGARH', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (604, 'NUH', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (619, 'PALWAL', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (70, 'PANCHKULA', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (71, 'PANIPAT', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (72, 'REWARI', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (73, 'ROHTAK', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (74, 'SIRSA', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (75, 'SONIPAT', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (76, 'YAMUNANAGAR', 6); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (15, 'BILASPUR', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (16, 'CHAMBA', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (17, 'HAMIRPUR', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (18, 'KANGRA', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (19, 'KINNAUR', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (20, 'KULLU', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (21, 'LAHUL AND SPITI', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (22, 'MANDI', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (23, 'SHIMLA', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (24, 'SIRMAUR', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (25, 'SOLAN', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (26, 'UNA', 2); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (1, 'ANANTNAG', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (623, 'BANDIPORA', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (3, 'BARAMULLA', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (2, 'Budgam', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (4, 'DODA', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (626, 'GANDERBAL', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (5, 'JAMMU', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (7, 'KATHUA', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (620, 'KISHTWAR', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (622, 'KULGAM', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (8, 'KUPWARA', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (10, 'POONCH', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (11, 'PULWAMA', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (12, 'RAJOURI', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (621, 'RAMBAN', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (627, 'REASI', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (624, 'SAMBA', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (625, 'SHOPIAN', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (13, 'SRINAGAR', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (14, 'UDHAMPUR', 1); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (322, 'BOKARO', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (323, 'CHATRA', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (324, 'DEOGHAR', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (325, 'DHANBAD', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (326, 'DUMKA', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (327, 'EAST SINGHBUM', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (328, 'GARHWA', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (329, 'GIRIDIH', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (330, 'GODDA', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (331, 'GUMLA', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (332, 'HAZARIBAGH', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (333, 'JAMTARA', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (606, 'KHUNTI', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (334, 'KODERMA', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (335, 'LATEHAR', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (336, 'LOHARDAGA', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (337, 'PAKUR', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (338, 'PALAMU', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (607, 'RAMGARH', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (339, 'RANCHI', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (340, 'SAHEBGANJ', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (341, 'SARAIKELA KHARSAWAN', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (342, 'SIMDEGA', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (343, 'WEST SINGHBHUM', 20); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (524, 'BAGALKOTE', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (528, 'BALLARI', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (527, 'BELAGAVI', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (526, 'BENGALURU RURAL', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (525, 'BENGALURU URBAN', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (529, 'BIDAR', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (531, 'CHAMARAJANAGARA', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (630, 'CHIKKABALLAPURA', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (532, 'CHIKKAMAGALURU', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (533, 'CHITRADURGA', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (534, 'DAKSHINA KANNADA', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (535, 'DAVANGERE', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (536, 'DHARWAD', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (537, 'GADAG', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (539, 'HASSAN', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (540, 'HAVERI', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (538, 'KALABURAGI', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (541, 'KODAGU', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (542, 'KOLAR', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (543, 'KOPPAL', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (544, 'MANDYA', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (545, 'MYSURU', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (546, 'RAICHUR', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (631, 'RAMANAGARA', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (547, 'SHIVAMOGGA', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (548, 'TUMAKURU', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (549, 'UDUPI', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (550, 'UTTARA KANNADA', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (738, 'VIJAYANAGAR', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (530, 'VIJAYAPURA', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (635, 'YADGIR', 29); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (554, 'ALAPPUZHA', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (555, 'ERNAKULAM', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (556, 'IDUKKI', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (557, 'KANNUR', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (558, 'KASARAGOD', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (559, 'KOLLAM', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (560, 'KOTTAYAM', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (561, 'KOZHIKODE', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (562, 'MALAPPURAM', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (563, 'PALAKKAD', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (564, 'PATHANAMTHITTA', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (565, 'THIRUVANANTHAPURAM', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (566, 'THRISSUR', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (567, 'WAYANAD', 32); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (6, 'KARGIL', 37); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (9, 'LEH LADAKH', 37); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (553, 'LAKSHADWEEP DISTRICT', 31); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (667, 'AGAR MALWA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (639, 'ALIRAJPUR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (390, 'ANUPPUR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (391, 'ASHOKNAGAR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (392, 'BALAGHAT', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (393, 'BARWANI', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (394, 'BETUL', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (395, 'BHIND', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (396, 'BHOPAL', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (397, 'BURHANPUR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (398, 'CHHATARPUR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (399, 'CHHINDWARA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (400, 'DAMOH', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (401, 'DATIA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (402, 'DEWAS', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (403, 'DHAR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (404, 'DINDORI', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (405, 'EAST NIMAR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (406, 'GUNA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (407, 'GWALIOR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (408, 'HARDA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (409, 'HOSHANGABAD', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (410, 'INDORE', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (411, 'JABALPUR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (412, 'JHABUA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (413, 'KATNI', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (414, 'KHARGONE', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (415, 'MANDLA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (416, 'MANDSAUR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (417, 'MORENA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (418, 'NARSINGHPUR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (419, 'NEEMUCH', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (722, 'Niwari', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (420, 'PANNA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (421, 'RAISEN', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (422, 'RAJGARH', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (423, 'RATLAM', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (424, 'REWA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (425, 'SAGAR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (426, 'SATNA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (427, 'SEHORE', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (428, 'SEONI', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (429, 'SHAHDOL', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (430, 'SHAJAPUR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (431, 'SHEOPUR', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (432, 'SHIVPURI', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (433, 'SIDHI', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (638, 'SINGRAULI', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (434, 'TIKAMGARH', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (435, 'UJJAIN', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (436, 'UMARIA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (437, 'VIDISHA', 23); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (466, 'AHMEDNAGAR', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (467, 'AKOLA', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (468, 'AMRAVATI', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (469, 'AURANGABAD', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (470, 'BEED', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (471, 'BHANDARA', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (472, 'BULDHANA', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (473, 'CHANDRAPUR', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (474, 'DHULE', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (475, 'GADCHIROLI', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (476, 'GONDIA', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (477, 'HINGOLI', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (478, 'JALGAON', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (479, 'JALNA', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (480, 'KOLHAPUR', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (481, 'LATUR', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (482, 'MUMBAI', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (483, 'MUMBAI SUBURBAN', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (484, 'NAGPUR', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (485, 'NANDED', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (486, 'NANDURBAR', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (487, 'NASHIK', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (488, 'OSMANABAD', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (665, 'PALGHAR', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (489, 'PARBHANI', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (490, 'PUNE', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (491, 'RAIGAD', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (492, 'RATNAGIRI', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (493, 'SANGLI', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (494, 'SATARA', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (495, 'SINDHUDURG', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (496, 'SOLAPUR', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (497, 'THANE', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (498, 'WARDHA', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (499, 'WASHIM', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (500, 'YAVATMAL', 27); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (252, 'BISHNUPUR', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (253, 'CHANDEL', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (254, 'CHURACHANDPUR', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (255, 'IMPHAL EAST', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (256, 'IMPHAL WEST', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (713, 'JIRIBAM', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (711, 'KAKCHING', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (717, 'KAMJONG', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (712, 'KANGPOKPI', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (714, 'NONEY', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (715, 'PHERZAWL', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (257, 'SENAPATI', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (258, 'TAMENGLONG', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (716, 'TENGNOUPAL', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (259, 'THOUBAL', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (260, 'UKHRUL', 14); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (740, 'EASTERN WEST KHASI HILLS', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (273, 'EAST GARO HILLS', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (657, 'EAST JAINTIA HILLS', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (274, 'EAST KHASI HILLS', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (656, 'NORTH GARO HILLS', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (276, 'RI BHOI', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (277, 'SOUTH GARO HILLS', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (663, 'SOUTH WEST GARO HILLS', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (658, 'SOUTH WEST KHASI HILLS', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (278, 'WEST GARO HILLS', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (275, 'WEST JAINTIA HILLS', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (279, 'WEST KHASI HILLS', 17); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (261, 'AIZAWL', 15); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (262, 'CHAMPHAI', 15); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (726, 'Hnahthial', 15); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (728, 'KHAWZAWL', 15); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (263, 'KOLASIB', 15); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (264, 'LAWNGTLAI', 15); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (265, 'LUNGLEI', 15); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (266, 'MAMIT', 15); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (267, 'SAIHA', 15); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (727, 'SAITUAL', 15); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (268, 'SERCHHIP', 15); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (244, 'DIMAPUR', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (614, 'KIPHIRE', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (245, 'KOHIMA', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (615, 'LONGLENG', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (246, 'MOKOKCHUNG', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (247, 'MON', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (736, 'Noklak', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (613, 'PEREN', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (248, 'PHEK', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (249, 'TUENSANG', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (250, 'WOKHA', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (251, 'ZUNHEBOTO', 13); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (344, 'ANUGUL', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (345, 'BALANGIR', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (346, 'BALESHWAR', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (347, 'BARGARH', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (348, 'BHADRAK', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (349, 'BOUDH', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (350, 'CUTTACK', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (351, 'DEOGARH', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (352, 'DHENKANAL', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (353, 'GAJAPATI', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (354, 'GANJAM', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (355, 'JAGATSINGHAPUR', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (356, 'JAJAPUR', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (357, 'JHARSUGUDA', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (358, 'KALAHANDI', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (359, 'KANDHAMAL', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (360, 'KENDRAPARA', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (361, 'KENDUJHAR', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (362, 'KHORDHA', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (363, 'KORAPUT', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (364, 'MALKANGIRI', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (365, 'MAYURBHANJ', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (366, 'NABARANGPUR', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (367, 'NAYAGARH', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (368, 'NUAPADA', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (369, 'PURI', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (370, 'RAYAGADA', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (371, 'SAMBALPUR', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (372, 'SONEPUR', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (373, 'SUNDARGARH', 21); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (598, 'KARAIKAL', 34); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (599, 'MAHE', 34); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (600, 'PONDICHERRY', 34); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (601, 'YANAM', 34); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (27, 'AMRITSAR', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (605, 'BARNALA', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (28, 'BATHINDA', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (29, 'FARIDKOT', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (30, 'FATEHGARH SAHIB', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (651, 'FAZILKA', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (31, 'FEROZEPUR', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (32, 'GURDASPUR', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (33, 'HOSHIARPUR', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (34, 'JALANDHAR', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (35, 'KAPURTHALA', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (36, 'LUDHIANA', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (737, 'MALERKOTLA', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (37, 'MANSA', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (38, 'MOGA', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (662, 'PATHANKOT', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (41, 'PATIALA', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (42, 'RUPNAGAR', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (43, 'SANGRUR', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (608, 'S.A.S Nagar', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (40, 'Shahid Bhagat Singh Nagar', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (39, 'SRI MUKTSAR SAHIB', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (609, 'Tarn Taran', 3); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (86, 'AJMER', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (87, 'ALWAR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (88, 'BANSWARA', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (89, 'BARAN', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (90, 'BARMER', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (91, 'BHARATPUR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (92, 'BHILWARA', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (93, 'BIKANER', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (94, 'BUNDI', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (95, 'CHITTORGARH', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (96, 'CHURU', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (97, 'DAUSA', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (98, 'DHOLPUR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (99, 'DUNGARPUR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (100, 'GANGANAGAR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (101, 'HANUMANGARH', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (102, 'JAIPUR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (103, 'JAISALMER', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (104, 'JALORE', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (105, 'JHALAWAR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (106, 'JHUNJHUNU', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (107, 'JODHPUR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (108, 'KARAULI', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (109, 'KOTA', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (110, 'NAGAUR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (111, 'PALI', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (629, 'PRATAPGARH', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (112, 'RAJSAMAND', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (113, 'SAWAI MADHOPUR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (114, 'SIKAR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (115, 'SIROHI', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (116, 'TONK', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (117, 'UDAIPUR', 8); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (225, 'Gangtok', 11); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (228, 'Gyalshing', 11); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (226, 'Mangan', 11); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (227, 'Namchi', 11); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (741, 'Pakyong', 11); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (742, 'Soreng', 11); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (610, 'Ariyalur', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (730, 'CHENGALPATTU', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (568, 'CHENNAI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (569, 'COIMBATORE', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (570, 'CUDDALORE', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (571, 'DHARMAPURI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (572, 'DINDIGUL', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (573, 'ERODE', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (729, 'KALLAKURICHI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (574, 'KANCHIPURAM', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (575, 'KANNIYAKUMARI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (576, 'KARUR', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (577, 'KRISHNAGIRI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (578, 'MADURAI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (735, 'Mayiladuthurai', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (579, 'NAGAPATTINAM', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (580, 'NAMAKKAL', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (581, 'PERAMBALUR', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (582, 'PUDUKKOTTAI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (583, 'RAMANATHAPURAM', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (731, 'Ranipet', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (584, 'SALEM', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (585, 'SIVAGANGA', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (733, 'TENKASI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (586, 'THANJAVUR', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (588, 'THENI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (587, 'THE NILGIRIS', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (589, 'THIRUVALLUR', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (590, 'THIRUVARUR', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (591, 'TIRUCHIRAPPALLI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (592, 'TIRUNELVELI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (732, 'Tirupathur', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (634, 'TIRUPPUR', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (593, 'TIRUVANNAMALAI', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (594, 'TUTICORIN', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (595, 'VELLORE', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (596, 'VILLUPURAM', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (597, 'VIRUDHUNAGAR', 33); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (501, 'ADILABAD', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (690, 'BHADRADRI KOTHAGUDEM', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (686, 'HANUMAKONDA', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (507, 'HYDERABAD', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (681, 'Jagitial', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (689, 'JANGOAN', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (687, 'JAYASHANKAR BHUPALAPALLY', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (695, 'JOGULAMBA GADWAL', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (685, 'KAMAREDDY', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (508, 'KARIMNAGAR', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (509, 'KHAMMAM', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (699, 'KUMURAM BHEEM ASIFABAD', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (688, 'MAHABUBABAD', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (512, 'MAHABUBNAGAR', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (684, 'MANCHERIAL', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (513, 'MEDAK', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (700, 'MEDCHAL MALKAJGIRI', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (720, 'Mulugu', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (694, 'NAGARKURNOOL', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (514, 'NALGONDA', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (721, 'Narayanpet', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (680, 'Nirmal', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (516, 'NIZAMABAD', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (682, 'PEDDAPALLI', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (683, 'RAJANNA SIRCILLA', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (518, 'RANGA REDDY', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (691, 'SANGAREDDY', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (692, 'SIDDIPET', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (696, 'SURYAPET', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (698, 'VIKARABAD', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (693, 'WANAPARTHY', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (522, 'WARANGAL', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (697, 'YADADRI BHUVANAGIRI', 36); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (465, 'DADRA AND NAGAR HAVELI', 38); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (463, 'DAMAN', 38); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (464, 'DIU', 38); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (269, 'Dhalai', 16); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (654, 'Gomati', 16); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (652, 'Khowai', 16); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (270, 'North Tripura', 16); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (653, 'Sepahijala', 16); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (271, 'South Tripura', 16); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (655, 'Unakoti', 16); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (272, 'West Tripura', 16); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (45, 'ALMORA', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (46, 'BAGESHWAR', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (47, 'CHAMOLI', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (48, 'CHAMPAWAT', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (49, 'DEHRADUN', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (50, 'HARIDWAR', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (51, 'NAINITAL', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (52, 'PAURI GARHWAL', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (53, 'PITHORAGARH', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (54, 'RUDRA PRAYAG', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (55, 'TEHRI GARHWAL', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (56, 'UDAM SINGH NAGAR', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (57, 'UTTAR KASHI', 5); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (118, 'AGRA', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (119, 'ALIGARH', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (121, 'AMBEDKAR NAGAR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (640, 'Amethi', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (154, 'AMROHA', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (122, 'AURAIYA', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (140, 'AYODHYA', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (123, 'AZAMGARH', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (124, 'BAGHPAT', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (125, 'BAHRAICH', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (126, 'BALLIA', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (127, 'BALRAMPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (128, 'BANDA', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (129, 'BARABANKI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (130, 'BAREILLY', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (131, 'BASTI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (179, 'BHADOHI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (132, 'BIJNOR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (133, 'BUDAUN', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (134, 'BULANDSHAHR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (135, 'CHANDAULI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (136, 'CHITRAKOOT', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (137, 'DEORIA', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (138, 'ETAH', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (139, 'ETAWAH', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (141, 'FARRUKHABAD', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (142, 'FATEHPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (143, 'FIROZABAD', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (144, 'GAUTAM BUDDHA NAGAR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (145, 'GHAZIABAD', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (146, 'GHAZIPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (147, 'GONDA', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (148, 'GORAKHPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (149, 'HAMIRPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (661, 'HAPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (150, 'HARDOI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (163, 'HATHRAS', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (151, 'JALAUN', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (152, 'JAUNPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (153, 'JHANSI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (155, 'KANNAUJ', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (156, 'KANPUR DEHAT', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (157, 'KANPUR NAGAR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (633, 'Kasganj', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (158, 'KAUSHAMBI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (159, 'KHERI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (160, 'KUSHI NAGAR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (161, 'LALITPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (162, 'LUCKNOW', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (164, 'MAHARAJGANJ', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (165, 'MAHOBA', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (166, 'MAINPURI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (167, 'MATHURA', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (168, 'MAU', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (169, 'MEERUT', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (170, 'MIRZAPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (171, 'MORADABAD', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (172, 'MUZAFFARNAGAR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (173, 'PILIBHIT', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (174, 'PRATAPGARH', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (120, 'PRAYAGRAJ', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (175, 'RAE BARELI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (176, 'RAMPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (177, 'SAHARANPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (659, 'SAMBHAL', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (178, 'SANT KABEER NAGAR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (180, 'SHAHJAHANPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (660, 'SHAMLI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (181, 'SHRAVASTI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (182, 'SIDDHARTH NAGAR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (183, 'SITAPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (184, 'SONBHADRA', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (185, 'SULTANPUR', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (186, 'UNNAO', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (187, 'VARANASI', 9); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (303, '24 PARAGANAS NORTH', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (304, '24 PARAGANAS SOUTH', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (664, 'Alipurduar', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (305, 'BANKURA', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (307, 'BIRBHUM', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (308, 'COOCHBEHAR', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (309, 'DARJEELING', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (310, 'DINAJPUR DAKSHIN', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (311, 'DINAJPUR UTTAR', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (312, 'HOOGHLY', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (313, 'HOWRAH', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (314, 'JALPAIGURI', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (703, 'Jhargram', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (702, 'KALIMPONG', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (315, 'KOLKATA', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (316, 'MALDAH', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (317, 'MEDINIPUR EAST', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (318, 'MEDINIPUR WEST', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (319, 'MURSHIDABAD', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (320, 'NADIA', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (704, 'PASCHIM BARDHAMAN', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (306, 'PURBA BARDHAMAN', 19); 
INSERT INTO m_district (district_id, district_name, state_id) VALUES (321, 'PURULIA', 19); 
