INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (35, 'ANDAMAN AND NICOBAR ISLANDS', 'U'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (28, 'ANDHRA PRADESH', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (12, 'ARUNACHAL PRADESH', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (18, 'ASSAM', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (10, 'BIHAR', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (4, 'CHANDIGARH', 'U'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (22, 'CHHATTISGARH', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (7, 'DELHI', 'U'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (30, 'GOA', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (24, 'GUJARAT', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (6, 'HARYANA', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (2, 'HIMACHAL PRADESH', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (1, 'JAMMU AND KASHMIR', 'U'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (20, 'JHARKHAND', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (29, 'KARNATAKA', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (32, 'KERALA', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (37, 'LADAKH', 'U'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (31, 'LAKSHADWEEP', 'U'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (23, 'MADHYA PRADESH', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (27, 'MAHARASHTRA', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (14, 'MANIPUR', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (17, 'MEGHALAYA', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (15, 'MIZORAM', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (13, 'NAGALAND', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (21, 'ODISHA', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (34, 'PUDUCHERRY', 'U'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (3, 'PUNJAB', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (8, 'RAJASTHAN', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (11, 'SIKKIM', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (33, 'TAMIL NADU', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (36, 'TELANGANA', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (38, 'THE DADRA AND NAGAR HAVELI AND DAMAN AND DIU', 'U'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (16, 'TRIPURA', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (5, 'UTTARAKHAND', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (9, 'UTTAR PRADESH', 'S'); 
INSERT INTO m_state (state_id, state_name, state_or_ut) VALUES (19, 'WEST BENGAL', 'S'); 
