FROM 166274191221.dkr.ecr.ap-south-1.amazonaws.com/aieze-node:12.22 AS build-node
WORKDIR /app
COPY . .
RUN npm install
RUN node node_modules/@angular/cli/bin/ng build --configuration=dev

FROM staticfloat/nginx-certbot
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build-node ./app/dist/hms-frontend-homepage/ /usr/share/nginx/html
RUN chmod -R 777 /usr/share/nginx/html
COPY ./conf.d /etc/nginx/conf.d/
COPY ./nginx.conf.dev /etc/nginx/nginx.conf
EXPOSE 80 443
